backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: "/public/uploads"
public_folder: "/uploads"
collections: 
  - name: "content"
    label: "Content"
    folder: "src/content"
    create: false
    slug: "{{slug}}"
    fields: 
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }